version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode : host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - practice_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static/
      - media:/data/media/
      - log:/var/log/nginx/
    secrets:
      - NGINX_AUTH

  django:
    image: practice:5
    networks:
      - practice_network
    volumes:
      - static:/home/pjw732/staticfiles/
      - media:/home/pjw732/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - practice_network
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD


networks:
  practice_network:

volumes:
  static:
  media:
  mariadb:
  log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true