version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - practice_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static/
      - media:/data/media/

  django:
    image: practice:4
    networks:
      - practice_network
    volumes:
      - static:/home/pjw732/staticfiles/
      - media:/home/pjw732/media/


networks:
  practice_network:

volumes:
  static:
  media: