version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - practice_network
    volumes:
      - /home/pjw732/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static/
      - media:/data/media/

  django:
    image: practice:4
    networks:
      - practice_network
    volumes:
      - static:/home/pjw732/staticfiles/
      - media:/home/pjw732/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - practice_network
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234


networks:
  practice_network:

volumes:
  static:
  media:
  mariadb: